# Generated by Django 4.0 on 2021-12-27 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='short',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Сокращенное слово'),
        ),
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.CharField(default='', max_length=20, verbose_name='Сокращенная ссылка'),
        ),
    ]
