# Generated by Django 4.0 on 2021-12-27 23:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('short_link', '0002_link_short_alter_link_short_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Пользователь'),
        ),
    ]
