# Generated by Django 4.0 on 2021-12-28 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0004_alter_link_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='id',
        ),
        migrations.AlterField(
            model_name='link',
            name='short',
            field=models.SlugField(default='', max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='Сокращенное слово'),
        ),
    ]
