# Generated by Django 4.0 on 2021-12-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0005_remove_link_id_alter_link_short'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='lohg_link',
            field=models.URLField(default='', max_length=250, unique=True, verbose_name='Длинная ссылка'),
        ),
    ]
