# Generated by Django 4.0 on 2021-12-28 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short_link', '0006_alter_link_lohg_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='short_link',
            field=models.URLField(default='', max_length=20, verbose_name='Сокращенная ссылка'),
        ),
    ]
