# Generated by Django 4.0 on 2021-12-27 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lohg_link', models.CharField(default='', max_length=250, unique=True, verbose_name='Длинная ссылка')),
                ('short_link', models.CharField(default='', max_length=10, unique=True, verbose_name='Сокращенная ссылка')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.profile')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
    ]
